/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kttddnsapi_util_InstancePW_GEN_UTIL */

#ifndef _Included_com_kttddnsapi_util_InstancePW_GEN_UTIL
#define _Included_com_kttddnsapi_util_InstancePW_GEN_UTIL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kttddnsapi_util_InstancePW_GEN_UTIL
 * Method:    ktt_cipher_makeInstantPasswd_C
 * Signature: (IIII[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kttddnsapi_util_InstancePW_1GEN_1UTIL_ktt_1cipher_1makeInstantPasswd_1C
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
